language: php

php:
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer update --prefer-source

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover